whatwg/compression

index.bs
index.html

This spec can temporarily be found at
https://ricea.github.io/compression/. Link to it there.

Update the URL to its temporary location

---

index.bs
index.html

There were two algorithms named "flush and enqueue", and it was confusing.
Rename them to "compress flush and enqueue" and "decompress flush and enqueue".

Rename "flush and enqueue" algorithms

---

index.bs
index.html

The spec linked to two different versions of WebIDL. Only link to the
latest version.

Fix duplicate WebIDL references

---

index.bs
index.html

Update the specification to explicitly list supported formats, and to
clarify exactly what conditions are considered errors for each format.
Also link some promise-related terms to the Web IDL standard.

Clarify supported formats and error handling

---

explainer.md

- Use monospace for `CompressionStream` and `DecompressionStream`.
- Provide citations for motivations.
- Remove redundant justification for initial choice of formats.

Miscellaneous explainer cleanups

---

index.bs
index.html

Change self-links and Github links to point to the WICG version of the
specification.
Also remove an unused link-defaults reference to the HTML standard.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/compression/pull/21.html" title="Last updated on Nov 28, 2019, 4:33 AM UTC (8af1965)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/compression/21/85b3211...8af1965.html" title="Last updated on Nov 28, 2019, 4:33 AM UTC (8af1965)">Diff</a>

Update metadata to point to WICG

---

index.bs
index.html

It's unnecessary to await a promise returned from an async function
(except if, as not needed here, the exception is to be caught in this
function instead of by a caller).
It's slightly verbose and advised against:
https://github.com/eslint/eslint/blob/master/docs/rules/no-return-await.md
https://jakearchibald.com/2017/await-vs-return-vs-return-await/
Since this is the only use of await, this function is not actually
async. Finally, it should be named with the same casing convention as
the previous example.
***
<a href="https://pr-preview.s3.amazonaws.com/jeremyroman/compression/pull/23.html" title="Last updated on Dec 5, 2019, 8:05 PM UTC (78ba8a2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/compression/23/1f86708...jeremyroman:78ba8a2.html" title="Last updated on …

In example code, simply return the promise from Response.blob.

---

explainer.md

The compressArrayBuffer() example uses "in" as a variable name. This
doesn't work because "in" is a keyword. Rename it to "data".

Avoid JS keyword in example

---

Makefile
index.bs
index.html

Follows https://github.com/whatwg/streams/pull/1073.
Also includes minor editorial touchups to the algorithms as I was editing them.
Do not merge until the Streams PR is merged, but feel free to review.
***
<a href="https://pr-preview.s3.amazonaws.com/domenic/compression/pull/35.html" title="Last updated on Sep 15, 2020, 6:21 PM UTC (b1d4905)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/compression/35/d3b7150...domenic:b1d4905.html" title="Last updated on Sep 15, 2020, 6:21 PM UTC (b1d4905)">Diff</a>

Use new Streams algorithms

---

index.bs
index.html

Follows https://github.com/whatwg/streams/pull/1110.
***
<a href="https://pr-preview.s3.amazonaws.com/domenic/compression/pull/36.html" title="Last updated on Mar 31, 2021, 3:58 PM UTC (69746c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/compression/36/eb2e6f8...domenic:69746c8.html" title="Last updated on Mar 31, 2021, 3:58 PM UTC (69746c8)">Diff</a>

Meta: use "set up" instead of "create" for TransformStreams

---

index.bs
index.html

Make the note about the use of "deflate" to refer to the "zlib" format
more prominent by rendering it as a note.
Also regenerate index.html, which has the side-effect of adding MDN
annotations.

Style the note about the naming of "deflate"

---

index.bs
index.html

Ref: tc39/proposal-shadowrealm#331
***
<a href="https://pr-preview.s3.amazonaws.com/Igalia/compression/pull/40.html" title="Last updated on Oct 20, 2021, 10:18 AM UTC (33a0696)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/compression/40/d2e9b4e...Igalia:33a0696.html" title="Last updated on Oct 20, 2021, 10:18 AM UTC (33a0696)">Diff</a>
***
<a href="https://pr-preview.s3.amazonaws.com/Igalia/compression/pull/40.html" title="Last updated on Jan 18, 2022, 10:36 AM UTC (36bb8ec)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/compression/40/e26f862...Igalia:36bb8ec.html" title="Last updated on Jan 18, 2022, 10:36 AM UTC (36bb8ec)">Diff</a>

Expose everywhere

---

index.bs
index.html

This change corrects a small spelling issue in Gzip-decompress a Blob to
Blob example, and adds an obsolete qualifier to the RFC7230 tag to ensure
the document compiles.
***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Aug 16, 2022, 12:59 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.
:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FWICG%2Fcompression%2F6d344f764d6fe03a67e8fbf804b960dee336686b%2Findex.bs&md-warning=not%20ready)
```
Error running …
```

Correct "decompressionStream" name in Gzip-decompress a Blob to Blob

---

index.bs
index.html

The standard was ambiguous about what DecompressionStream should do if there is data after the BFINAL block. Clarify that it is an error.
Fixes #47.
***
<a href="https://pr-preview.s3.amazonaws.com/WICG/compression/pull/49.html" title="Last updated on Mar 2, 2023, 11:36 AM UTC (57bb24b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/compression/49/8e3b2c4...57bb24b.html" title="Last updated on Mar 2, 2023, 11:36 AM UTC (57bb24b)">Diff</a>

deflate-raw: Disallow input data after BFINAL

---

index.bs

***
<a href="https://whatpr.org/compression/60.html" title="Last updated on May 28, 2024, 2:42 PM UTC (9cef4c6)">Preview</a> | <a href="https://whatpr.org/compression/60/34d39f1...9cef4c6.html" title="Last updated on May 28, 2024, 2:42 PM UTC (9cef4c6)">Diff</a>

Compression is a WHATWG standard now

---

index.bs

It turns out "compressionstandard" is too many characters, so we picked up "compressionapi" instead.
***
<a href="https://whatpr.org/compression/62.html" title="Last updated on May 30, 2024, 2:29 AM UTC (51347c9)">Preview</a> | <a href="https://whatpr.org/compression/62/a6ec498...51347c9.html" title="Last updated on May 30, 2024, 2:29 AM UTC (51347c9)">Diff</a>

Meta: update Twitter account

---

index.bs

Closes #61.
***
<a href="https://whatpr.org/compression/63.html" title="Last updated on May 30, 2024, 2:38 AM UTC (f0b712e)">Preview</a> | <a href="https://whatpr.org/compression/63/a6ec498...f0b712e.html" title="Last updated on May 30, 2024, 2:38 AM UTC (f0b712e)">Diff</a>

Editorial: clean up conformance section and references

---

index.bs

* Wrap the `<pre>`s in `<div>`s to work better with the WHATWG stylesheet.
* Add IDs to suppress Bikeshed warnings
* Clean up the code a bit for the deflate-compress example, notably by using async iteration.
***
<a href="https://whatpr.org/compression/64.html" title="Last updated on May 30, 2024, 2:44 AM UTC (ed2b0bc)">Preview</a> | <a href="https://whatpr.org/compression/64/a6ec498...ed2b0bc.html" title="Last updated on May 30, 2024, 2:44 AM UTC (ed2b0bc)">Diff</a>

Editorial: clean up examples

---

index.bs

Right now everything is just italics. (Using `|var|` makes it `<var>` instead of `<em>` and enables linting for variables. One should also be able to click variables to highlight.)
***
<a href="https://whatpr.org/compression/70.html" title="Last updated on Feb 24, 2025, 11:53 PM UTC (7d137ec)">Preview</a> | <a href="https://whatpr.org/compression/70/ec763b0...7d137ec.html" title="Last updated on Feb 24, 2025, 11:53 PM UTC (7d137ec)">Diff</a>

Editorial: use bikeshed variable syntax

---

index.bs

Fixes #68
***
<a href="https://whatpr.org/compression/69.html" title="Last updated on Feb 26, 2025, 11:29 AM UTC (b9d97fa)">Preview</a> | <a href="https://whatpr.org/compression/69/66dae67...b9d97fa.html" title="Last updated on Feb 26, 2025, 11:29 AM UTC (b9d97fa)">Diff</a>

Editorial: link to Infra for "For each"
